### ISSUE TITLE
Generated Normalmaps are pink

### ISSUE THREAD

**Issue by BrodyB** [maxartz15/MA_TextureAtlasser#10]
Hey there!

Thanks so much for making this tool. I can see it saving us a ton of time if we can get past this issue.

When generating atlases with normal maps, the resulting normal maps have a pink hue to them:

![TestAtlas_Normal](https://user-images.githubusercontent.com/2968043/158486553-f219d258-8f23-47c1-85c9-a7b1e8bcc715.png)

The normal map textures I'm feeding into the tool are marked as Normal Map and use default settings, and this issue seems to crop up whether or not the resulting atlas ends up resizing the original or not.

Details:
* Unity 2021.2.14f1
* Using High-Definition Render Pipeline
* MA_TextureAtlasser code from latest commit ([05b4ea9](https://github.com/maxartz15/MA_TextureAtlasser/commit/05b4ea9f8063fce7b53f20cabeaf28624db5a142))

**Comment by maxartz15** [comment]
Hey,

From my quick test in 2020.3.28f1 HDRP it seems that the exported normal map is not marked as normal map in the import settings.
After exporting put it too normal map and see if that fixes the issue.

Setup:
![Setup](https://user-images.githubusercontent.com/27885649/158491509-9b7f7b57-801e-4db5-b565-bb45c8073b1c.png)

Export:
![Export](https://user-images.githubusercontent.com/27885649/158491700-74b48caa-f4d9-4ac5-814b-03a4c066ad4e.png)

I hope this helps, else there might be an other issue.

**Comment by BrodyB** [comment]
Sorry for the late follow-up on this.

Turns out what the issue was was a conflict with an asset post processor script I have in our project that affected new texture assets coming in.

Sorry about the alarm!

**Comment by maxartz15** [comment]
np, good luck with your project.
