### ISSUE TITLE
Texture width is used as height

### ISSUE THREAD

**Issue by TheMadDodger** [maxartz15/MA_TextureAtlasser#2]
A typo in MA_TextureUtils.cs on line 44 causes the copied texture to be the wrong size if the height is different from the width, this is the second time I had to fix this myself as updating it to the latest version still includes this exact same typo.

Texture2D myTexture2D = new Texture2D(texture.width, texture.width);
should be:
Texture2D myTexture2D = new Texture2D(texture.width, texture.height);

Please test your tool before uploading/updating it!!!

Also a suggestion: the exporting of the textures happens to one single folder, would be nice if you get a prompt to select where you want to save the textures, or maybe even have the path in the export settings.

**Comment by TheMadDodger** [comment]
Also, the tool has compiler errors when you try to make a build.

**Comment by maxartz15** [comment]
> A typo in MA_TextureUtils.cs on line 44 causes the copied texture to be the wrong size

Thanks for finding this bug, I think the main reason why I haven't found it yet is because I only used squared textures with this tool.

> Also, the tool has compiler errors when you try to make a build.

Forgot to include the define #if UNITY_EDITOR in MA_TextureAtlasserProExportSettings.cs, this should now be fixed as well.

Version 1.7.3 is now available to test.
https://github.com/maxartz15/MA_TextureAtlasser/releases/tag/1.7.3

**Comment by maxartz15** [comment]
> Also a suggestion: the exporting of the textures happens to one single folder, would be nice if you get a prompt to select where you want to save the textures, or maybe even have the path in the export settings.

Thanks for the suggestion, I will be looking at this for the next version. If you could open a new issue for this, that would be great. (then I can close this one.)
