### ISSUE TITLE
ReplaceAtlasMesh only change memory in unity not files?

### ISSUE THREAD

**Issue by leon49** [maxartz15/MA_TextureAtlasser#3]
After i exported(using ReplaceMesh of ModelFormat),it only change the memory of meshes in unity. Git tools show no files have changed,and i restart unity,changes is revert.

**Comment by leon49** [comment]
> After i exported(using ReplaceMesh of ModelFormat),it only change the memory of meshes in unity. Git tools show no files have changed,and i restart unity,changes is revert.

test in Unity 2019.3

**Comment by leon49** [comment]
OK !  I know the reason..
Because the meshes of my problem is from .fbx file.
It is not a unity asset file.
So even you set it dirty,it can not be saved.

**Comment by maxartz15** [comment]
> OK ! I know the reason..
> Because the meshes of my problem is from .fbx file.
> It is not a unity asset file.
> So even you set it dirty,it can not be saved.

Thanks for mentioning this. 
If we can't find a fix for this, then we probably have to rewrite the .fbx file itself. When that is the case the 'ReplaceMesh' option should be removed and replaced with export as .fbx (a check to replace can then be added, same for obj).
