### ISSUE TITLE
Model Export

### ISSUE THREAD

**Issue by Devostated** [maxartz15/MA_TextureAtlasser#5]
Hello,
when I export the models gain a new pivot point, so they get out of place and have a wrong scale by 100.
Here is an example:
Orange is from your tool
Blue is original which doesn't use an atlas
![image](https://user-images.githubusercontent.com/30211694/102118317-d1e15780-3e3f-11eb-8418-a9457dfa7b03.png)

**Comment by Devostated** [comment]
Actually I figured it's a unity "problem", besides the scale

**Comment by maxartz15** [comment]
Hi @Devostated is the problem still there? If so, could you attach the model? Then I can have a look at it.

**Comment by Devostated** [comment]
Hey,
it's my first day of unity, so I'm sorry if I say something wrong.
Here is a model to test. It scales down by the factor of 100 
[bed.zip](https://github.com/maxartz15/MA_TextureAtlasser/files/5691323/bed.zip)

Another thing is that textures get stretched. I'm pretty sure that my UVs are too just too awful inorder to work properly.
![image](https://user-images.githubusercontent.com/30211694/102130166-cb0f1080-3e50-11eb-8ae0-8b373b6dd8ec.png)

Here is a screenshot of the original UV, as you can see a lot is outside of the square, which makes it all so complicated.
![image](https://user-images.githubusercontent.com/30211694/102130947-c7c85480-3e51-11eb-8ef4-243b46287cda.png)

**Comment by maxartz15** [comment]
So I opened the bed in Unity and Blender, the model is indeed off. The pivot point is way off and the imported scale is 100 (which should be 1). You could fix this in a 3D modelling tool or play around with the model import scale factor within Unity.
![image](https://user-images.githubusercontent.com/27885649/102131353-5f2da780-3e52-11eb-9ac0-20d7441cda18.png)

You could try turning on/off the texture wrap settings, but I'm not sure it will fix it.
![image](https://user-images.githubusercontent.com/27885649/102131558-ab78e780-3e52-11eb-9342-e4104ad0ad8b.png)
Else it might be that some of the UV coordinates are just above the 0..1 range and so will be moved back one unit by the tool.
![image](https://user-images.githubusercontent.com/27885649/102132605-18d94800-3e54-11eb-9c11-43c59b4efa2e.png)

**Comment by Devostated** [comment]
The pivot point works correctly if you change the Tool Handle Position from center to pivot it works before Export.

 This is how it looks with UV Wrap disabled, I guess I have to fix the UVs somehow manually.
![image](https://user-images.githubusercontent.com/30211694/102133813-fcd6a600-3e55-11eb-86c6-a8a173c2a9b3.png)

or What exactly are UV channels? Maybe I can do something with that?

**Comment by maxartz15** [comment]
A model can have multiple UV channels. They are basically multiple sets of UV unwraps that can be used for different purposes. By default most models have their base UV in channel 0 and then Unity generates light-map UV's for channel 2.

I suggest that you leave UV Wrap on and make sure that the UV's are within the 0..1 range.
