### ISSUE TITLE
Unable to select URP Standard shaders

### ISSUE THREAD

**Issue by NemesisTWarlock** [maxartz15/MA_TextureAtlasser#7]
Hi, It seems that I am unable to select any of the URP versions of the Standard shaders, such as URP/Lit or URP/Simple Lit. they do not show up in the export window when choosing a shader to export to.

I can currently work around this by simply setting it to the Legacy "Standard" shader, and then manually switching the exported material to a URP standard shader.

Would it be possible to add support for directly exporting to a non-shadergraph SRP shader in a future build?

**Comment by maxartz15** [comment]
Hi, you can find the URP/HDRP shaders when you browse the packages folder in the project panel, you can drag and drop them from there. Or sometimes you can see them by toggling the eye icon when looking for the shaders.

You can see I had the same problem here in [this](https://youtu.be/kx5Pbrtba-4?t=108) video.

**Comment by NemesisTWarlock** [comment]
Thanks for the heads up! I'll do this in the future.
